// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, Endpoint, HandlerFunction } from './types';

export { Metadata, Endpoint, HandlerFunction };

import login_account from './account/login-account';
import refresh_token_account from './account/refresh-token-account';
import create_sale_v1 from './v1/create-sale-v1';
import get_admins_v1 from './v1/get-admins-v1';
import get_business_structures_v1 from './v1/get-business-structures-v1';
import get_time_zones_v1 from './v1/get-time-zones-v1';
import create_v1_approval_matrix from './v1/approval-matrix/create-v1-approval-matrix';
import retrieve_v1_approval_matrix from './v1/approval-matrix/retrieve-v1-approval-matrix';
import update_v1_approval_matrix from './v1/approval-matrix/update-v1-approval-matrix';
import list_v1_approval_matrix from './v1/approval-matrix/list-v1-approval-matrix';
import create_buyer_v1_roles from './v1/buyer/roles/create-buyer-v1-roles';
import retrieve_buyer_v1_roles from './v1/buyer/roles/retrieve-buyer-v1-roles';
import update_buyer_v1_roles from './v1/buyer/roles/update-buyer-v1-roles';
import list_buyer_v1_roles from './v1/buyer/roles/list-buyer-v1-roles';
import count_buyer_v1_roles from './v1/buyer/roles/count-buyer-v1-roles';
import list_users_buyer_v1_roles from './v1/buyer/roles/list-users-buyer-v1-roles';
import create_buyer_v1_users from './v1/buyer/users/create-buyer-v1-users';
import retrieve_buyer_v1_users from './v1/buyer/users/retrieve-buyer-v1-users';
import update_buyer_v1_users from './v1/buyer/users/update-buyer-v1-users';
import list_buyer_v1_users from './v1/buyer/users/list-buyer-v1-users';
import count_buyer_v1_users from './v1/buyer/users/count-buyer-v1-users';
import create_v1_category from './v1/category/create-v1-category';
import retrieve_v1_category from './v1/category/retrieve-v1-category';
import update_v1_category from './v1/category/update-v1-category';
import list_v1_category from './v1/category/list-v1-category';
import delete_v1_category from './v1/category/delete-v1-category';
import update_bulk_v1_category from './v1/category/update-bulk-v1-category';
import retrieve_v1_category_prefix from './v1/category-prefix/retrieve-v1-category-prefix';
import update_v1_category_prefix from './v1/category-prefix/update-v1-category-prefix';
import list_v1_category_prefix from './v1/category-prefix/list-v1-category-prefix';
import delete_v1_category_prefix from './v1/category-prefix/delete-v1-category-prefix';
import bulk_update_v1_category_prefix from './v1/category-prefix/bulk-update-v1-category-prefix';
import create_v1_class from './v1/class/create-v1-class';
import retrieve_v1_class from './v1/class/retrieve-v1-class';
import update_v1_class from './v1/class/update-v1-class';
import list_v1_class from './v1/class/list-v1-class';
import delete_v1_class from './v1/class/delete-v1-class';
import bulk_update_v1_class from './v1/class/bulk-update-v1-class';
import update_v1_currency from './v1/currency/update-v1-currency';
import list_v1_currency from './v1/currency/list-v1-currency';
import get_exchange_rate_v1_currency from './v1/currency/get-exchange-rate-v1-currency';
import retrieve_dash_board_v1_settings from './v1/dash-board/settings/retrieve-dash-board-v1-settings';
import update_dash_board_v1_settings from './v1/dash-board/settings/update-dash-board-v1-settings';
import create_v1_dining_option from './v1/dining-option/create-v1-dining-option';
import retrieve_v1_dining_option from './v1/dining-option/retrieve-v1-dining-option';
import update_v1_dining_option from './v1/dining-option/update-v1-dining-option';
import list_v1_dining_option from './v1/dining-option/list-v1-dining-option';
import retrieve_v1_entity_prefix from './v1/entity-prefix/retrieve-v1-entity-prefix';
import update_v1_entity_prefix from './v1/entity-prefix/update-v1-entity-prefix';
import list_v1_entity_prefix from './v1/entity-prefix/list-v1-entity-prefix';
import delete_v1_entity_prefix from './v1/entity-prefix/delete-v1-entity-prefix';
import bulk_update_v1_entity_prefix from './v1/entity-prefix/bulk-update-v1-entity-prefix';
import retrieve_v1_generic_item from './v1/generic-item/retrieve-v1-generic-item';
import list_v1_generic_item from './v1/generic-item/list-v1-generic-item';
import create_v1_location from './v1/location/create-v1-location';
import retrieve_v1_location from './v1/location/retrieve-v1-location';
import update_v1_location from './v1/location/update-v1-location';
import list_v1_location from './v1/location/list-v1-location';
import count_all_v1_location from './v1/location/count-all-v1-location';
import get_hierarchy_v1_location from './v1/location/get-hierarchy-v1-location';
import get_hierarchy_by_active_v1_location from './v1/location/get-hierarchy-by-active-v1-location';
import list_all_v1_location from './v1/location/list-all-v1-location';
import update_bulk_v1_location from './v1/location/update-bulk-v1-location';
import create_v1_market_place_app from './v1/market-place-app/create-v1-market-place-app';
import retrieve_v1_market_place_app from './v1/market-place-app/retrieve-v1-market-place-app';
import update_v1_market_place_app from './v1/market-place-app/update-v1-market-place-app';
import delete_v1_market_place_app from './v1/market-place-app/delete-v1-market-place-app';
import install_v1_market_place_app from './v1/market-place-app/install-v1-market-place-app';
import search_v1_market_place_app from './v1/market-place-app/search-v1-market-place-app';
import uninstall_v1_market_place_app from './v1/market-place-app/uninstall-v1-market-place-app';
import create_v1_menu_item from './v1/menu-item/create-v1-menu-item';
import retrieve_v1_menu_item from './v1/menu-item/retrieve-v1-menu-item';
import update_v1_menu_item from './v1/menu-item/update-v1-menu-item';
import list_v1_menu_item from './v1/menu-item/list-v1-menu-item';
import bulk_update_v1_menu_item from './v1/menu-item/bulk-update-v1-menu-item';
import count_v1_menu_item from './v1/menu-item/count-v1-menu-item';
import get_brand_location_dining_options_v1_menu_item from './v1/menu-item/get-brand-location-dining-options-v1-menu-item';
import get_ingredient_list_v1_menu_item from './v1/menu-item/get-ingredient-list-v1-menu-item';
import create_v1_modifier from './v1/modifier/create-v1-modifier';
import retrieve_v1_modifier from './v1/modifier/retrieve-v1-modifier';
import update_v1_modifier from './v1/modifier/update-v1-modifier';
import list_v1_modifier from './v1/modifier/list-v1-modifier';
import bulk_update_v1_modifier from './v1/modifier/bulk-update-v1-modifier';
import count_v1_modifier from './v1/modifier/count-v1-modifier';
import get_brand_location_dining_options_v1_modifier from './v1/modifier/get-brand-location-dining-options-v1-modifier';
import get_ingredient_list_v1_modifier from './v1/modifier/get-ingredient-list-v1-modifier';
import create_v1_modifier_group from './v1/modifier-group/create-v1-modifier-group';
import retrieve_v1_modifier_group from './v1/modifier-group/retrieve-v1-modifier-group';
import update_v1_modifier_group from './v1/modifier-group/update-v1-modifier-group';
import list_v1_modifier_group from './v1/modifier-group/list-v1-modifier-group';
import delete_v1_modifier_group from './v1/modifier-group/delete-v1-modifier-group';
import bulk_update_v1_modifier_group from './v1/modifier-group/bulk-update-v1-modifier-group';
import count_v1_modifier_group from './v1/modifier-group/count-v1-modifier-group';
import retrieve_v1_prefix_configuration from './v1/prefix-configuration/retrieve-v1-prefix-configuration';
import get_code_v1_prefix_configuration from './v1/prefix-configuration/get-code-v1-prefix-configuration';
import create_v1_prep_item from './v1/prep-item/create-v1-prep-item';
import retrieve_v1_prep_item from './v1/prep-item/retrieve-v1-prep-item';
import update_v1_prep_item from './v1/prep-item/update-v1-prep-item';
import list_v1_prep_item from './v1/prep-item/list-v1-prep-item';
import bulk_update_v1_prep_item from './v1/prep-item/bulk-update-v1-prep-item';
import count_v1_prep_item from './v1/prep-item/count-v1-prep-item';
import get_current_stock_v1_prep_item from './v1/prep-item/get-current-stock-v1-prep-item';
import get_ingredient_list_v1_prep_item from './v1/prep-item/get-ingredient-list-v1-prep-item';
import get_stock_changes_v1_prep_item from './v1/prep-item/get-stock-changes-v1-prep-item';
import create_v1_inventoryitem from './v1/inventoryitem/create-v1-inventoryitem';
import retrieve_v1_inventoryitem from './v1/inventoryitem/retrieve-v1-inventoryitem';
import update_v1_inventoryitem from './v1/inventoryitem/update-v1-inventoryitem';
import list_v1_inventoryitem from './v1/inventoryitem/list-v1-inventoryitem';
import delete_v1_inventoryitem from './v1/inventoryitem/delete-v1-inventoryitem';
import bulk_update_v1_inventoryitem from './v1/inventoryitem/bulk-update-v1-inventoryitem';
import count_v1_inventoryitem from './v1/inventoryitem/count-v1-inventoryitem';
import current_stock_v1_inventoryitem from './v1/inventoryitem/current-stock-v1-inventoryitem';
import rollback_transaction_v1_inventoryitem from './v1/inventoryitem/rollback-transaction-v1-inventoryitem';
import stock_changes_v1_inventoryitem from './v1/inventoryitem/stock-changes-v1-inventoryitem';
import upload_import_file_v1_inventoryitem from './v1/inventoryitem/upload-import-file-v1-inventoryitem';
import create_v1_production from './v1/production/create-v1-production';
import retrieve_v1_production from './v1/production/retrieve-v1-production';
import update_v1_production from './v1/production/update-v1-production';
import list_v1_production from './v1/production/list-v1-production';
import approve_v1_production from './v1/production/approve-v1-production';
import bulk_update_v1_production from './v1/production/bulk-update-v1-production';
import change_to_edit_post_v1_production from './v1/production/change-to-edit-post-v1-production';
import count_v1_production from './v1/production/count-v1-production';
import lock_unlock_v1_production from './v1/production/lock-unlock-v1-production';
import reject_v1_production from './v1/production/reject-v1-production';
import submit_for_approval_v1_production from './v1/production/submit-for-approval-v1-production';
import create_v1_purchase_option from './v1/purchase-option/create-v1-purchase-option';
import retrieve_v1_purchase_option from './v1/purchase-option/retrieve-v1-purchase-option';
import update_v1_purchase_option from './v1/purchase-option/update-v1-purchase-option';
import list_v1_purchase_option from './v1/purchase-option/list-v1-purchase-option';
import delete_v1_purchase_option from './v1/purchase-option/delete-v1-purchase-option';
import list_suppliers_v1_purchase_option from './v1/purchase-option/list-suppliers-v1-purchase-option';
import create_v1_purchase_order from './v1/purchase-order/create-v1-purchase-order';
import retrieve_v1_purchase_order from './v1/purchase-order/retrieve-v1-purchase-order';
import update_v1_purchase_order from './v1/purchase-order/update-v1-purchase-order';
import list_v1_purchase_order from './v1/purchase-order/list-v1-purchase-order';
import add_receiving_v1_purchase_order from './v1/purchase-order/add-receiving-v1-purchase-order';
import count_v1_purchase_order from './v1/purchase-order/count-v1-purchase-order';
import list_items_v1_purchase_order from './v1/purchase-order/list-items-v1-purchase-order';
import list_receiving_v1_purchase_order from './v1/purchase-order/list-receiving-v1-purchase-order';
import update_status_v1_purchase_order from './v1/purchase-order/update-status-v1-purchase-order';
import create_v1_purchase_request from './v1/purchase-request/create-v1-purchase-request';
import retrieve_v1_purchase_request from './v1/purchase-request/retrieve-v1-purchase-request';
import update_v1_purchase_request from './v1/purchase-request/update-v1-purchase-request';
import list_v1_purchase_request from './v1/purchase-request/list-v1-purchase-request';
import approve_v1_purchase_request from './v1/purchase-request/approve-v1-purchase-request';
import bulk_update_v1_purchase_request from './v1/purchase-request/bulk-update-v1-purchase-request';
import count_v1_purchase_request from './v1/purchase-request/count-v1-purchase-request';
import reject_v1_purchase_request from './v1/purchase-request/reject-v1-purchase-request';
import submit_v1_purchase_request from './v1/purchase-request/submit-v1-purchase-request';
import list_v1_reports from './v1/reports/list-v1-reports';
import bulk_update_v1_reports from './v1/reports/bulk-update-v1-reports';
import create_v1_requisition_queue from './v1/requisition-queue/create-v1-requisition-queue';
import list_v1_requisition_queue from './v1/requisition-queue/list-v1-requisition-queue';
import create_v1_requisition_template from './v1/requisition-template/create-v1-requisition-template';
import retrieve_v1_requisition_template from './v1/requisition-template/retrieve-v1-requisition-template';
import update_v1_requisition_template from './v1/requisition-template/update-v1-requisition-template';
import list_v1_requisition_template from './v1/requisition-template/list-v1-requisition-template';
import count_v1_requisition_template from './v1/requisition-template/count-v1-requisition-template';
import update_bulk_v1_requisition_template from './v1/requisition-template/update-bulk-v1-requisition-template';
import create_v1_return_order from './v1/return-order/create-v1-return-order';
import retrieve_v1_return_order from './v1/return-order/retrieve-v1-return-order';
import update_v1_return_order from './v1/return-order/update-v1-return-order';
import list_v1_return_order from './v1/return-order/list-v1-return-order';
import approve_v1_return_order from './v1/return-order/approve-v1-return-order';
import count_v1_return_order from './v1/return-order/count-v1-return-order';
import eligible_items_v1_return_order from './v1/return-order/eligible-items-v1-return-order';
import items_detail_v1_return_order from './v1/return-order/items-detail-v1-return-order';
import lock_unlock_v1_return_order from './v1/return-order/lock-unlock-v1-return-order';
import reject_v1_return_order from './v1/return-order/reject-v1-return-order';
import submit_v1_return_order from './v1/return-order/submit-v1-return-order';
import update_status_v1_return_order from './v1/return-order/update-status-v1-return-order';
import create_v1_roles from './v1/roles/create-v1-roles';
import retrieve_v1_roles from './v1/roles/retrieve-v1-roles';
import update_v1_roles from './v1/roles/update-v1-roles';
import list_v1_roles from './v1/roles/list-v1-roles';
import add_user_role_v1_roles from './v1/roles/add-user-role-v1-roles';
import delete_remove_user_role_v1_roles from './v1/roles/delete-remove-user-role-v1-roles';
import retrieve_count_v1_roles from './v1/roles/retrieve-count-v1-roles';
import retrieve_users_v1_roles from './v1/roles/retrieve-users-v1-roles';
import retrieve_section_v1_section from './v1/section/retrieve-section-v1-section';
import section_v1_section from './v1/section/section-v1-section';
import update_section_v1_section from './v1/section/update-section-v1-section';
import update_update_bulk_v1_section from './v1/section/update-update-bulk-v1-section';
import retrieve_v1_storage_area from './v1/storage-area/retrieve-v1-storage-area';
import retrieve_storage_area_v1_storage_area from './v1/storage-area/retrieve-storage-area-v1-storage-area';
import storage_area_v1_storage_area from './v1/storage-area/storage-area-v1-storage-area';
import update_storage_area_v1_storage_area from './v1/storage-area/update-storage-area-v1-storage-area';
import retrieve_v1_supplier from './v1/supplier/retrieve-v1-supplier';
import retrieve_count_v1_supplier from './v1/supplier/retrieve-count-v1-supplier';
import retrieve_supplier_v1_supplier from './v1/supplier/retrieve-supplier-v1-supplier';
import supplier_v1_supplier from './v1/supplier/supplier-v1-supplier';
import update_bulk_update_v1_supplier from './v1/supplier/update-bulk-update-v1-supplier';
import update_supplier_v1_supplier from './v1/supplier/update-supplier-v1-supplier';
import retrieve_v1_system_tax_setting from './v1/system-tax-setting/retrieve-v1-system-tax-setting';
import delete_system_tax_setting_v1_system_tax_setting from './v1/system-tax-setting/delete-system-tax-setting-v1-system-tax-setting';
import retrieve_system_tax_setting_v1_system_tax_setting from './v1/system-tax-setting/retrieve-system-tax-setting-v1-system-tax-setting';
import seed_initial_data_to_elastic_search_v1_system_tax_setting from './v1/system-tax-setting/seed-initial-data-to-elastic-search-v1-system-tax-setting';
import system_tax_setting_v1_system_tax_setting from './v1/system-tax-setting/system-tax-setting-v1-system-tax-setting';
import update_system_tax_setting_v1_system_tax_setting from './v1/system-tax-setting/update-system-tax-setting-v1-system-tax-setting';
import retrieve_v1_transaction_prefix from './v1/transaction-prefix/retrieve-v1-transaction-prefix';
import delete_transaction_prefix_v1_transaction_prefix from './v1/transaction-prefix/delete-transaction-prefix-v1-transaction-prefix';
import retrieve_transaction_prefix_v1_transaction_prefix from './v1/transaction-prefix/retrieve-transaction-prefix-v1-transaction-prefix';
import update_bulk_update_transaction_prefix_v1_transaction_prefix from './v1/transaction-prefix/update-bulk-update-transaction-prefix-v1-transaction-prefix';
import update_transaction_prefix_v1_transaction_prefix from './v1/transaction-prefix/update-transaction-prefix-v1-transaction-prefix';
import retrieve_transfer_v1_transfer_in from './v1/transfer/transfer-in/retrieve-transfer-v1-transfer-in';
import approve_transfer_v1_transfer_in from './v1/transfer/transfer-in/approve-transfer-v1-transfer-in';
import finalize_transfer_v1_transfer_in from './v1/transfer/transfer-in/finalize-transfer-v1-transfer-in';
import receive_transfer_v1_transfer_in from './v1/transfer/transfer-in/receive-transfer-v1-transfer-in';
import reject_transfer_v1_transfer_in from './v1/transfer/transfer-in/reject-transfer-v1-transfer-in';
import retrieve_count_transfer_v1_transfer_in from './v1/transfer/transfer-in/retrieve-count-transfer-v1-transfer-in';
import retrieve_transfer_in_transfer_v1_transfer_in from './v1/transfer/transfer-in/retrieve-transfer-in-transfer-v1-transfer-in';
import submit_transfer_v1_transfer_in from './v1/transfer/transfer-in/submit-transfer-v1-transfer-in';
import transfer_in_transfer_v1_transfer_in from './v1/transfer/transfer-in/transfer-in-transfer-v1-transfer-in';
import update_transfer_in_transfer_v1_transfer_in from './v1/transfer/transfer-in/update-transfer-in-transfer-v1-transfer-in';
import retrieve_transfer_v1_transfer_out from './v1/transfer/transfer-out/retrieve-transfer-v1-transfer-out';
import approve_transfer_v1_transfer_out from './v1/transfer/transfer-out/approve-transfer-v1-transfer-out';
import finalize_transfer_v1_transfer_out from './v1/transfer/transfer-out/finalize-transfer-v1-transfer-out';
import fulfill_transfer_v1_transfer_out from './v1/transfer/transfer-out/fulfill-transfer-v1-transfer-out';
import reject_transfer_v1_transfer_out from './v1/transfer/transfer-out/reject-transfer-v1-transfer-out';
import retrieve_count_transfer_v1_transfer_out from './v1/transfer/transfer-out/retrieve-count-transfer-v1-transfer-out';
import retrieve_transfer_out_transfer_v1_transfer_out from './v1/transfer/transfer-out/retrieve-transfer-out-transfer-v1-transfer-out';
import submit_transfer_v1_transfer_out from './v1/transfer/transfer-out/submit-transfer-v1-transfer-out';
import transfer_out_transfer_v1_transfer_out from './v1/transfer/transfer-out/transfer-out-transfer-v1-transfer-out';
import update_transfer_out_transfer_v1_transfer_out from './v1/transfer/transfer-out/update-transfer-out-transfer-v1-transfer-out';
import retrieve_waste_reason_v1_waste_reason from './v1/waste-reason/retrieve-waste-reason-v1-waste-reason';
import waste_reason_v1_waste_reason from './v1/waste-reason/waste-reason-v1-waste-reason';

export const endpoints: Endpoint[] = [];

function addEndpoint(endpoint: Endpoint) {
  endpoints.push(endpoint);
}

addEndpoint(login_account);
addEndpoint(refresh_token_account);
addEndpoint(create_sale_v1);
addEndpoint(get_admins_v1);
addEndpoint(get_business_structures_v1);
addEndpoint(get_time_zones_v1);
addEndpoint(create_v1_approval_matrix);
addEndpoint(retrieve_v1_approval_matrix);
addEndpoint(update_v1_approval_matrix);
addEndpoint(list_v1_approval_matrix);
addEndpoint(create_buyer_v1_roles);
addEndpoint(retrieve_buyer_v1_roles);
addEndpoint(update_buyer_v1_roles);
addEndpoint(list_buyer_v1_roles);
addEndpoint(count_buyer_v1_roles);
addEndpoint(list_users_buyer_v1_roles);
addEndpoint(create_buyer_v1_users);
addEndpoint(retrieve_buyer_v1_users);
addEndpoint(update_buyer_v1_users);
addEndpoint(list_buyer_v1_users);
addEndpoint(count_buyer_v1_users);
addEndpoint(create_v1_category);
addEndpoint(retrieve_v1_category);
addEndpoint(update_v1_category);
addEndpoint(list_v1_category);
addEndpoint(delete_v1_category);
addEndpoint(update_bulk_v1_category);
addEndpoint(retrieve_v1_category_prefix);
addEndpoint(update_v1_category_prefix);
addEndpoint(list_v1_category_prefix);
addEndpoint(delete_v1_category_prefix);
addEndpoint(bulk_update_v1_category_prefix);
addEndpoint(create_v1_class);
addEndpoint(retrieve_v1_class);
addEndpoint(update_v1_class);
addEndpoint(list_v1_class);
addEndpoint(delete_v1_class);
addEndpoint(bulk_update_v1_class);
addEndpoint(update_v1_currency);
addEndpoint(list_v1_currency);
addEndpoint(get_exchange_rate_v1_currency);
addEndpoint(retrieve_dash_board_v1_settings);
addEndpoint(update_dash_board_v1_settings);
addEndpoint(create_v1_dining_option);
addEndpoint(retrieve_v1_dining_option);
addEndpoint(update_v1_dining_option);
addEndpoint(list_v1_dining_option);
addEndpoint(retrieve_v1_entity_prefix);
addEndpoint(update_v1_entity_prefix);
addEndpoint(list_v1_entity_prefix);
addEndpoint(delete_v1_entity_prefix);
addEndpoint(bulk_update_v1_entity_prefix);
addEndpoint(retrieve_v1_generic_item);
addEndpoint(list_v1_generic_item);
addEndpoint(create_v1_location);
addEndpoint(retrieve_v1_location);
addEndpoint(update_v1_location);
addEndpoint(list_v1_location);
addEndpoint(count_all_v1_location);
addEndpoint(get_hierarchy_v1_location);
addEndpoint(get_hierarchy_by_active_v1_location);
addEndpoint(list_all_v1_location);
addEndpoint(update_bulk_v1_location);
addEndpoint(create_v1_market_place_app);
addEndpoint(retrieve_v1_market_place_app);
addEndpoint(update_v1_market_place_app);
addEndpoint(delete_v1_market_place_app);
addEndpoint(install_v1_market_place_app);
addEndpoint(search_v1_market_place_app);
addEndpoint(uninstall_v1_market_place_app);
addEndpoint(create_v1_menu_item);
addEndpoint(retrieve_v1_menu_item);
addEndpoint(update_v1_menu_item);
addEndpoint(list_v1_menu_item);
addEndpoint(bulk_update_v1_menu_item);
addEndpoint(count_v1_menu_item);
addEndpoint(get_brand_location_dining_options_v1_menu_item);
addEndpoint(get_ingredient_list_v1_menu_item);
addEndpoint(create_v1_modifier);
addEndpoint(retrieve_v1_modifier);
addEndpoint(update_v1_modifier);
addEndpoint(list_v1_modifier);
addEndpoint(bulk_update_v1_modifier);
addEndpoint(count_v1_modifier);
addEndpoint(get_brand_location_dining_options_v1_modifier);
addEndpoint(get_ingredient_list_v1_modifier);
addEndpoint(create_v1_modifier_group);
addEndpoint(retrieve_v1_modifier_group);
addEndpoint(update_v1_modifier_group);
addEndpoint(list_v1_modifier_group);
addEndpoint(delete_v1_modifier_group);
addEndpoint(bulk_update_v1_modifier_group);
addEndpoint(count_v1_modifier_group);
addEndpoint(retrieve_v1_prefix_configuration);
addEndpoint(get_code_v1_prefix_configuration);
addEndpoint(create_v1_prep_item);
addEndpoint(retrieve_v1_prep_item);
addEndpoint(update_v1_prep_item);
addEndpoint(list_v1_prep_item);
addEndpoint(bulk_update_v1_prep_item);
addEndpoint(count_v1_prep_item);
addEndpoint(get_current_stock_v1_prep_item);
addEndpoint(get_ingredient_list_v1_prep_item);
addEndpoint(get_stock_changes_v1_prep_item);
addEndpoint(create_v1_inventoryitem);
addEndpoint(retrieve_v1_inventoryitem);
addEndpoint(update_v1_inventoryitem);
addEndpoint(list_v1_inventoryitem);
addEndpoint(delete_v1_inventoryitem);
addEndpoint(bulk_update_v1_inventoryitem);
addEndpoint(count_v1_inventoryitem);
addEndpoint(current_stock_v1_inventoryitem);
addEndpoint(rollback_transaction_v1_inventoryitem);
addEndpoint(stock_changes_v1_inventoryitem);
addEndpoint(upload_import_file_v1_inventoryitem);
addEndpoint(create_v1_production);
addEndpoint(retrieve_v1_production);
addEndpoint(update_v1_production);
addEndpoint(list_v1_production);
addEndpoint(approve_v1_production);
addEndpoint(bulk_update_v1_production);
addEndpoint(change_to_edit_post_v1_production);
addEndpoint(count_v1_production);
addEndpoint(lock_unlock_v1_production);
addEndpoint(reject_v1_production);
addEndpoint(submit_for_approval_v1_production);
addEndpoint(create_v1_purchase_option);
addEndpoint(retrieve_v1_purchase_option);
addEndpoint(update_v1_purchase_option);
addEndpoint(list_v1_purchase_option);
addEndpoint(delete_v1_purchase_option);
addEndpoint(list_suppliers_v1_purchase_option);
addEndpoint(create_v1_purchase_order);
addEndpoint(retrieve_v1_purchase_order);
addEndpoint(update_v1_purchase_order);
addEndpoint(list_v1_purchase_order);
addEndpoint(add_receiving_v1_purchase_order);
addEndpoint(count_v1_purchase_order);
addEndpoint(list_items_v1_purchase_order);
addEndpoint(list_receiving_v1_purchase_order);
addEndpoint(update_status_v1_purchase_order);
addEndpoint(create_v1_purchase_request);
addEndpoint(retrieve_v1_purchase_request);
addEndpoint(update_v1_purchase_request);
addEndpoint(list_v1_purchase_request);
addEndpoint(approve_v1_purchase_request);
addEndpoint(bulk_update_v1_purchase_request);
addEndpoint(count_v1_purchase_request);
addEndpoint(reject_v1_purchase_request);
addEndpoint(submit_v1_purchase_request);
addEndpoint(list_v1_reports);
addEndpoint(bulk_update_v1_reports);
addEndpoint(create_v1_requisition_queue);
addEndpoint(list_v1_requisition_queue);
addEndpoint(create_v1_requisition_template);
addEndpoint(retrieve_v1_requisition_template);
addEndpoint(update_v1_requisition_template);
addEndpoint(list_v1_requisition_template);
addEndpoint(count_v1_requisition_template);
addEndpoint(update_bulk_v1_requisition_template);
addEndpoint(create_v1_return_order);
addEndpoint(retrieve_v1_return_order);
addEndpoint(update_v1_return_order);
addEndpoint(list_v1_return_order);
addEndpoint(approve_v1_return_order);
addEndpoint(count_v1_return_order);
addEndpoint(eligible_items_v1_return_order);
addEndpoint(items_detail_v1_return_order);
addEndpoint(lock_unlock_v1_return_order);
addEndpoint(reject_v1_return_order);
addEndpoint(submit_v1_return_order);
addEndpoint(update_status_v1_return_order);
addEndpoint(create_v1_roles);
addEndpoint(retrieve_v1_roles);
addEndpoint(update_v1_roles);
addEndpoint(list_v1_roles);
addEndpoint(add_user_role_v1_roles);
addEndpoint(delete_remove_user_role_v1_roles);
addEndpoint(retrieve_count_v1_roles);
addEndpoint(retrieve_users_v1_roles);
addEndpoint(retrieve_section_v1_section);
addEndpoint(section_v1_section);
addEndpoint(update_section_v1_section);
addEndpoint(update_update_bulk_v1_section);
addEndpoint(retrieve_v1_storage_area);
addEndpoint(retrieve_storage_area_v1_storage_area);
addEndpoint(storage_area_v1_storage_area);
addEndpoint(update_storage_area_v1_storage_area);
addEndpoint(retrieve_v1_supplier);
addEndpoint(retrieve_count_v1_supplier);
addEndpoint(retrieve_supplier_v1_supplier);
addEndpoint(supplier_v1_supplier);
addEndpoint(update_bulk_update_v1_supplier);
addEndpoint(update_supplier_v1_supplier);
addEndpoint(retrieve_v1_system_tax_setting);
addEndpoint(delete_system_tax_setting_v1_system_tax_setting);
addEndpoint(retrieve_system_tax_setting_v1_system_tax_setting);
addEndpoint(seed_initial_data_to_elastic_search_v1_system_tax_setting);
addEndpoint(system_tax_setting_v1_system_tax_setting);
addEndpoint(update_system_tax_setting_v1_system_tax_setting);
addEndpoint(retrieve_v1_transaction_prefix);
addEndpoint(delete_transaction_prefix_v1_transaction_prefix);
addEndpoint(retrieve_transaction_prefix_v1_transaction_prefix);
addEndpoint(update_bulk_update_transaction_prefix_v1_transaction_prefix);
addEndpoint(update_transaction_prefix_v1_transaction_prefix);
addEndpoint(retrieve_transfer_v1_transfer_in);
addEndpoint(approve_transfer_v1_transfer_in);
addEndpoint(finalize_transfer_v1_transfer_in);
addEndpoint(receive_transfer_v1_transfer_in);
addEndpoint(reject_transfer_v1_transfer_in);
addEndpoint(retrieve_count_transfer_v1_transfer_in);
addEndpoint(retrieve_transfer_in_transfer_v1_transfer_in);
addEndpoint(submit_transfer_v1_transfer_in);
addEndpoint(transfer_in_transfer_v1_transfer_in);
addEndpoint(update_transfer_in_transfer_v1_transfer_in);
addEndpoint(retrieve_transfer_v1_transfer_out);
addEndpoint(approve_transfer_v1_transfer_out);
addEndpoint(finalize_transfer_v1_transfer_out);
addEndpoint(fulfill_transfer_v1_transfer_out);
addEndpoint(reject_transfer_v1_transfer_out);
addEndpoint(retrieve_count_transfer_v1_transfer_out);
addEndpoint(retrieve_transfer_out_transfer_v1_transfer_out);
addEndpoint(submit_transfer_v1_transfer_out);
addEndpoint(transfer_out_transfer_v1_transfer_out);
addEndpoint(update_transfer_out_transfer_v1_transfer_out);
addEndpoint(retrieve_waste_reason_v1_waste_reason);
addEndpoint(waste_reason_v1_waste_reason);

export type Filter = {
  type: 'resource' | 'operation' | 'tag' | 'tool';
  op: 'include' | 'exclude';
  value: string;
};

export function query(filters: Filter[], endpoints: Endpoint[]): Endpoint[] {
  const allExcludes = filters.length > 0 && filters.every((filter) => filter.op === 'exclude');
  const unmatchedFilters = new Set(filters);

  const filtered = endpoints.filter((endpoint: Endpoint) => {
    let included = false || allExcludes;

    for (const filter of filters) {
      if (match(filter, endpoint)) {
        unmatchedFilters.delete(filter);
        included = filter.op === 'include';
      }
    }

    return included;
  });

  // Check if any filters didn't match
  const unmatched = Array.from(unmatchedFilters).filter((f) => f.type === 'tool' || f.type === 'resource');
  if (unmatched.length > 0) {
    throw new Error(
      `The following filters did not match any endpoints: ${unmatched
        .map((f) => `${f.type}=${f.value}`)
        .join(', ')}`,
    );
  }

  return filtered;
}

function match({ type, value }: Filter, endpoint: Endpoint): boolean {
  switch (type) {
    case 'resource': {
      const regexStr = '^' + normalizeResource(value).replace(/\*/g, '.*') + '$';
      const regex = new RegExp(regexStr);
      return regex.test(normalizeResource(endpoint.metadata.resource));
    }
    case 'operation':
      return endpoint.metadata.operation === value;
    case 'tag':
      return endpoint.metadata.tags.includes(value);
    case 'tool':
      return endpoint.tool.name === value;
  }
}

function normalizeResource(resource: string): string {
  return resource.toLowerCase().replace(/[^a-z.*\-_]*/g, '');
}
